require 'yaml'

ENV["COCOAPODS_DISABLE_STATS"] = "1"

platform :ios, '11.0'

workspace 'FantLab'

project 'FantLab.xcodeproj'
project 'Modules.xcodeproj'

use_modular_headers!

def release_pods
    pod 'Firebase/Core', :configurations => ['Adhoc', 'Release']
    pod 'Fabric', :configurations => ['Adhoc', 'Release']
    pod 'Crashlytics', :configurations => ['Adhoc', 'Release']
end

def all_pods
    release_pods

    pod 'RxSwift', '4.4.2'
    pod 'YYWebImage', '1.0.5'
    pod 'ALLKit', :git => 'https://github.com/geor-kasapidi/ALLKit', :commit => '80aea2ed613029fcc489f17096f7f0c2fa9348c5'
end

target 'FantLab' do
    project 'FantLab.xcodeproj'

    all_pods

    target 'FantLabTests' do
        inherit! :search_paths
    end
end

modules = YAML.load_file('Modules.yaml')

modules.keys.sort.each do |target_name|
    target target_name do
        project 'Modules.xcodeproj'

        all_pods
    end
end
