require 'yaml'

ENV["COCOAPODS_DISABLE_STATS"] = "1"

platform :ios, '11.0'

workspace 'FantLab'

project 'FantLab.xcodeproj'
project 'Modules.xcodeproj'

use_modular_headers!
inhibit_all_warnings!

def release_pods
    pod 'Firebase/Core', :configurations => ['Adhoc', 'Release']
    pod 'Fabric', :configurations => ['Adhoc', 'Release']
    pod 'Crashlytics', :configurations => ['Adhoc', 'Release']
end

def all_pods
    release_pods

    pod 'RxSwift', '5.0.0'
    pod 'RxRelay', '5.0.0'
    pod 'Nuke', '8.2.0'
    pod 'PinIt', '1.0'
    pod 'ALLKit', '1.0'
end

target 'FantLab' do
    project 'FantLab.xcodeproj'

    all_pods

    target 'FantLabTests' do
        inherit! :search_paths
    end
end

modules = YAML.load_file('Modules.yaml')

modules.keys.sort.each do |target_name|
    target target_name do
        project 'Modules.xcodeproj'

        all_pods
    end
end
